# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET localhost:8000/api/v1/timecode/Z4CyURj01oo?key_words=гипотеза римана,Дзета функция,аналитическое продолжение функции
Accept: application/json

###

GET localhost:8000/api/v1/timecode/6xnzxuV_AVA?key_words=алгоритмическая разрешимость и доказуемость,теория доказательств,теория алгоритмов,теория сложности
Accept: application/json

###

GET localhost:8000/api/v1/timecode/XSvQ4gQigk4?key_words=год И.Н. Лобачевского,геометрия Евклида,геометрия Лобачевского,основание геометрии,непротиворечивость геометрии Лобачевского
Accept: application/json

###

GET localhost:8000/api/v1/timecode/kcTsIZnjhag?key_words=кубические уравнения,неприводимый случай кубических уравнений,Теорема Молламе,теорема Гельдера,уравнения четвертой степени,метод Феррари,Рафаэль Бомбелли,работы Бомбелли,комплексные числа,основная теорема алгебры,Фаньяно деи Тоски Джулио Карл,работы Фаньяно,Леонард Эйлер,работы Эйлера,Жозеф Луи Лагранж,работы Лагранжа,Пауло Руффини,работы Руффини,Нальс Хенрик Абель,работы Абеля,Эварист Галуа,работы Галуа
Accept: application/json

###

GET localhost:8000/api/v1/timecode/XlrHsrZU0sE?key_words=слово
