# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

### 1 https://www.youtube.com/watch?v=Z4CyURj01oo

GET localhost:8000/api/v1/timecode/Z4CyURj01oo?key_words=гипотеза римана,Дзета функция,аналитическое продолжение функции
Accept: application/json

### 2 https://www.youtube.com/watch?v=6xnzxuV_AVA

GET localhost:8000/api/v1/timecode/6xnzxuV_AVA?key_words=алгоритмическая разрешимость и доказуемость,теория доказательств,теория алгоритмов,теория сложности
Accept: application/json

### 3 https://www.youtube.com/watch?v=XSvQ4gQigk4

GET localhost:8000/api/v1/timecode/XSvQ4gQigk4?key_words=год И.Н. Лобачевского,геометрия Евклида,геометрия Лобачевского,основание геометрии,непротиворечивость геометрии Лобачевского
Accept: application/json

### 4 https://www.youtube.com/watch?v=kcTsIZnjhag

GET localhost:8000/api/v1/timecode/kcTsIZnjhag?key_words=кубические уравнения,неприводимый случай кубических уравнений,Теорема Молламе,теорема Гельдера,уравнения четвертой степени,метод Феррари,Рафаэль Бомбелли,работы Бомбелли,комплексные числа,основная теорема алгебры,Фаньяно деи Тоски Джулио Карл,работы Фаньяно,Леонард Эйлер,работы Эйлера,Жозеф Луи Лагранж,работы Лагранжа,Пауло Руффини,работы Руффини,Нальс Хенрик Абель,работы Абеля,Эварист Галуа,работы Галуа
Accept: application/json

### 5 https://www.youtube.com/watch?v=yxtV2HBnEbo нет субтитров

GET localhost:8000/api/v1/timecode/yxtV2HBnEbo?key_words= год И.Н. Лобачевского,вклад Эратосфена,во сколько раз солнце дальше чем луна,во сколько раз солнце больше луны,вычисление размеров луны и солнца,геоцентрическая система Птолемея,доказательство невозможности геоцентрической системы

### 6 https://www.youtube.com/watch?v=zoOsbXT14z8

GET localhost:8000/api/v1/timecode/zoOsbXT14z8?key_words=год Н.И. Лобачевского,задача Диофанта,DPRM-теорема,диофантовы уравнения,десятая проблема Гильберта

### 7 https://www.youtube.com/watch?v=DmjtCPxGNIA

GET localhost:8000/api/v1/timecode/DmjtCPxGNIA?key_words=год И.Н. Лобачевского,задачи принятия решений,задача об обтимальном выборе,правило относительного большинства,правило Борда,правило Кондросе,метод попарных сравнений,теорема Эрроу,Пространство исходов,вероятность,условная вероятность,независимость событий,случайные величины,стратегия Келли,формула Байеса,машинное обучение,байесовская классификация,персептрон,алгоритм обучения персептрона

### 8 https://www.youtube.com/watch?v=ZxxttP758e0 - нет именованных сущностей

GET localhost:8000/api/v1/timecode/ZxxttP758e0?key_words=деление на ноль,стереографическая проекция,корень из отрицательного числа,логарифм отрицательного числа,дифференцировать не дифференцируемое,суммировать расходящееся

### 9 https://www.youtube.com/watch?v=BCaPNZ-qgHg - нет субтитров

GET localhost:8000/api/v1/timecode/BCaPNZ-qgHg?key_words=учителя Н.И. Лобачевского в гимназии,наставления Н.И. Лобачевского учителям математики в гимназиях,приватные ученики Н.И. Лобачевского,Н.И. Лобачевский о воспитании

### 10 https://www.youtube.com/watch?v=2xlTvIEltAs

GET localhost:8000/api/v1/timecode/2xlTvIEltAs?key_words=год И.Н. Лобачевского,биография Н.И. Лобачевского,труды Н. И. Лобачевского,геометрия Лобачевского

### 11 https://www.youtube.com/watch?v=3JQSVOmOPMI - нет субтитров

GET localhost:8000/api/v1/timecode/3JQSVOmOPMI?key_words=год И.Н. Лобачевского,Планиметрия Лобачевского,модель Бельтрами- Клейна,пятый постулат,краткая история создания неевклидовой геометрии,движение плоскости Лобачевского

### 12 https://www.youtube.com/watch?v=1s_DZcaYapE - нет субтитров

GET localhost:8000/api/v1/timecode/1s_DZcaYapE?key_words=геометрия Евклида, геометрия Лобачевского,модели плоскости Лобачевского,степень искривления пространства,геометрия пространства-времени,геодезические линии,гравитационные линзы

### 13 https://www.youtube.com/watch?v=U-_YfRlHCkg - нет субтитров

GET localhost:8000/api/v1/timecode/U-_YfRlHCkg?key_words=год И.Н. Лобачевского,Шифр Цезаря,династия Котельниковых,криптография,обработка данных в форме натуральных чисел,шифр Вернама,проблема распределения секретных ключей,криптография с открытым ключом,односторонние функции,шифрование,дешифрование,протокол Диффи-Хеллмана,квантовый компьютер

### 14 https://www.youtube.com/watch?v=1bFqa55Me1I

GET localhost:8000/api/v1/timecode/1bFqa55Me1I?key_words=математическое моделирование, вид Антарктиды с космоса, геофизический метроном, климат прошлого

### 15 https://www.youtube.com/watch?v=VHfyYSw3TCQ

GET localhost:8000/api/v1/timecode/VHfyYSw3TCQ?key_words=год И.Н. Лобачевского,Знаменитые математические проблемы

### 16 https://www.youtube.com/watch?v=ArNxyRVf83o - нет субтитров

GET localhost:8000/api/v1/timecode/ArNxyRVf83o?key_words=год И.Н. Лобачевского,неклассическая логика,у порога воображаемой логики,проблема истолкования частных суждений,«метод Лобачевского»,психологизм в логике,металогика,предвосхищение ключевых принципов современной неклассической логики,логические идеи Н.А. Васильева

###

GET localhost:8000/api/v1/timecode/labUUV1ZEIA?key_words=регрессия,логистическая,нейрон,персептрон,градиент,спуск,обучение,корреляция,артем

###
GET localhost:8000/api/v1/timecode/XlrHsrZU0sE?key_words=слово
